language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gfortran
    - os: osx 
      osx_image: xcode8.2
      env: OSX=10.12
      compiler: clang
    - os: osx
      osx_image: xcode8
      env: OSX=10.11
      compiler: clang
    - os: osx
      osx_image: xcode6.4
      env: OSX=10.10
      compiler: clang
  allow_failures:
    - os: osx

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  export PLATFORM=osx$OSX-x86_64-clang`clang -dumpversion`; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install bash gcc; brew link --overwrite gcc; gfortran --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PLATFORM=linux-x86_64-gcc`gcc -dumpversion`; fi
  - git clone https://github.com/coin-or-tools/BuildTools
  - bash BuildTools/get.dependencies.sh fetch > /dev/null

script:
  - bash BuildTools/get.dependencies.sh build --verbosity=2 --test

