Description:
  Slug: CHiPPS-BiCePS
  ShortName: BiCePS
  LongName: Branch, Constrain, and Price Software
  ShortDescription: The data management layer for the CHiPPS parallel search class hierarchy.
  LongDescription: |2
    The Branch, Constrain, and Price Software (BiCePS) is a data management
    layer for CHiPPS, the COIN-OR High Performance Parallel Search Framework.
    CHiPPS is a framework for implementing parallel algorithms based on tree
    search. BiCePS is built on top of ALPS and provides functionality for
    implementing relaxation-based branch-and-bound algorithms.
  Manager: Ted Ralphs, ted at lehigh dot edu 
  Homepage: https://github.com/coin-or/CHiPPS-BiCePS
  License: Eclipse Public License 2.0
  LicenseURL: http://www.opensource.org/licenses/eclipse-2.0
  Zenodo: 23726997
  IncludedIn:
    Package: CHiPPS-BLIS
  Language:
    - C++
  Categories: 
    - Optimization deterministic linear discrete
    - Optimization utility
  PaperCite: http://dx.doi.org/10.1023/B:SUPE.0000020179.55383.ad

Dependencies:
  - Description: Sample data files
    URL: https://projects.coin-or.org/svn/Data/Sample/stable/1.2
    Version: 1.2
    Required: Required
  - Description: COIN-OR Utilities
    URL: https://projects.coin-or.org/svn/CoinUtils/trunk/CoinUtils
    Version: 2.11
    Required: Required
  - Description: Open Solver Interface
    URL: https://projects.coin-or.org/svn/Osi/stable/0.107/Osi
    Version: 0.108
    Required: Required
  - Description: COIN-OR LP Solver
    URL: https://projects.coin-or.org/svn/Clp/stable/1.16/Clp
    Version: 1.17
    Required: Required
  - Description: Cut Generation Library
    URL: https://projects.coin-or.org/svn/Cgl/stable/0.59/Cgl
    Version: 0.60
    Required: Required
  - Description: Abstract Library for Parallel Search
    URL: https://github.com/coin-or/CHiPPS-ALPS
    Version: 2.0
    Required: Required
  - Description: Basic Linear Algebra Subroutines (BLAS)
    URL: http://www.netlib.org/blas
    Required: Recommended
  - Description: Linear Algebra Package (LAPACK)
    URL: http://www.netlib.org/lapack
    Required: Recommended
  - Description: GNU Readline
    Required: Recommended
  - Description: GNU History
    Required: Recommended

DevelopmentStatus: 
  activityStatus: Active
  maturityLevel: 5
  testedPlatforms: 
  - operatingSystem: Linux
    compiler: gcc
  - operatingSystem: Mac OS X
    compiler:
    - gcc
    - clang
  - operatingSystem: Microsoft Windows
    compiler: cl
  - operatingSystem: Microsoft Windows with MSys2
    compiler:
    - gcc
    - cl
    - icl
  - operatingSystem: Microsoft Windows Subsystem for Linux
    compiler:
    - gcc
    - cl
    - icl
